language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
addons:
  firefox: 45.8.0esr
env:
- PLONE_VERSION=5.0
- PLONE_VERSION=5.1
matrix:
  allow_failures:
  - env: PLONE_VERSION=5.0
  fast_finish: true
install:
- sed -ie "s#test-5.1.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
- virtualenv -p python2.7 .
- bin/pip install -r requirements.txt
- bin/buildout annotate
- bin/buildout
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage --output-dir=htmlcov -t "--layer=!Robot"
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
